name: CI
on: [push, pull_request]
jobs:
    cs-check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master
            - name: cache-composer
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-7.4-${{ github.sha }}
            - name: setup
              uses: shivammathur/setup-php@2.9.0
              with:
                  php-version: 8.0
                  extensions: mbstring, fileinfo, json, intl, dom
            - name: install
              run: composer update --prefer-stable
            - name: 'php-cs-fixer check'
              run: 'vendor/bin/php-cs-fixer fix --dry-run --diff'
              env:
                  PHP_CS_FIXER_IGNORE_ENV: 1
            - name: 'phpstan check'
              run: 'vendor/bin/phpstan analyse'

    tests:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 15
            matrix:
                php-versions:  ['8.0', '8.1']
        name: tests-${{ matrix.php-versions }}
        steps:
            - name: checkout
              uses: actions/checkout@master
            - name: cache-composer
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-${{ matrix.php-versions }}-${{ github.sha }}
            - name: setup
              uses: shivammathur/setup-php@2.9.0
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, fileinfo, json, intl, dom
            - name: composer install
              run: composer update --prefer-stable
            - name: tests
              run: vendor/bin/phpunit --exclude-group none
